### ISSUE TITLE
Change bower:cf task name to bower:process

### ISSUE THREAD

**Issue by anselmbradford** [cfpb/generator-cf#68]
See https://github.com/cfpb/generator-cf/blob/master/app/templates/_Gruntfile.js#L34 

Why is this task called bower:cf? It appears to install all bower dependencies from bower.json, not just cf packages. This is currently called "install" in cfgov-refresh and OAH and I'm just wondering if it was intentionally changed to cf for some reason I'm not seeing?

**Comment by contolini** [comment]
generator-cf's bower task is a little different from cfgov-refresh's. The generator implemented [these changes](https://github.com/cfpb/capital-framework/issues/84) proposed by @himedlooff a while back. I think I changed the name from `install` to `cf` because the task no longer installs the bower components (see [line 37](https://github.com/cfpb/generator-cf/blob/master/app/templates/_Gruntfile.js#L37)). It mostly just cleans up the components folder.

You're right, though, that it doesn't only touch CF components so `cf` is a misnomer. Maybe we should change it to something like `bower:process`?

**Comment by jimmynotjim** [comment]
cfgov-refresh will also be [updating in the future](https://github.com/cfpb/cfgov-refresh/blob/project-standardize/Gruntfile.js#L29-L47) to match the generator. There's no reason to re-install every package, that's what the manager is there for. `process` sounds like a fine task name to me.

**Comment by anselmbradford** [comment]
Cool I'll go with `process` for the update to cfgov-refresh gruntfile I'm working on. That link @contolini posted gives great context for the two vendor directories too. Looks like they could be consolidated.

**Comment by contolini** [comment]
Be gone ye bower task!

![tumblr_mdemydvxpq1qedb29o1_500](https://cloud.githubusercontent.com/assets/1060248/8041885/7c2dbb44-0de9-11e5-979c-9594d2c567b2.gif)
