### ISSUE TITLE
Bower exportsOverrides appear to alphabetized, except...

### ISSUE THREAD

**Issue by anselmbradford** [cfpb/generator-cf#74]
`exportsOverrides` entries in `bower.json` appear to be alphabetized, except
https://github.com/cfpb/generator-cf/blob/master/app/templates/_bower.json#L26-L28
doesn't appear first in the list.

**Comment by contolini** [comment]
Death to exportsOverrides.

**Comment by himedlooff** [comment]
I love `exportsOverrides ` : (

![70s-head-shake](https://cloud.githubusercontent.com/assets/1093373/8046855/8ca27da2-0e0c-11e5-864d-dc371d251e05.gif)

**Comment by Scotchester** [comment]
@himedlooff Me, too, man. Me, too. But it did cause tons of problems.

I think the next best thing is that we should use the `ignore` property liberally in our components' `bower.json` files, so that we're installing only what we absolutely need to. We can't control it for outside packages, but we can keep our own house in order.

**Comment by contolini** [comment]
Sorry. :pensive: If there's critical mass we can add it back. To me it has always felt like unnecessary over-engineering.

**Comment by Scotchester** [comment]
Nah, probably not. I was more expressing nostalgia than genuine desire to
bring it back.

Since you figured out the pure `@import` method, it is a lot less useful.

**Comment by himedlooff** [comment]
It's all good, if this makes it simpler I'm all for it. =)
